ssetup = [
    [ {'nx':1, 'ny':1},  
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1} ], 
    [ {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1} ],
    [ {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1} ],
    [ {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':1, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1},
      {'nx':2, 'ny':1} ],
    [ {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':2},
      {'nx':2, 'ny':2},
      {'nx':2, 'ny':2} ],
    [ {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':2},
      {'nx':2, 'ny':2},
      {'nx':2, 'ny':2} ],
    [ {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':1, 'rotation': 90},
      {'nx':2, 'ny':2},
      {'nx':2, 'ny':2},
      {'nx':2, 'ny':2} ],
    ]
